### ISSUE TITLE
Gems declared in Gemfile aren't available in gemspec

### ISSUE THREAD

**Issue by sgerrand** [Accuity/rspec-puppet-utils#6]
When I bring this gem into a puppet project to test, the dependencies declared in the `Gemfile` aren't brought in. This causes prepending `bundle exec` to explode. :sob: 

This example demonstrates the issue:

`Gemfile`:

```
source 'https://rubygems.org'

gem 'rspec-puppet-utils'
```

`Gemfile.lock`:

```
GEM
  remote: https://rubygems.org/
  specs:
    rspec-puppet-utils (2.2.1)

PLATFORMS
  ruby

DEPENDENCIES
  rspec-puppet-utils

BUNDLED WITH
   1.10.6
```

**Comment by TomPoulton** [comment]
Thanks for spotting this @sgerrand 

This is fixed in v2.2.2
